import java.util.List;

/**
 * 
 */
public class RegisterCarsPurchased 
{
    List<Car> carsSold;

    /**
     * 
     * @param carsSold
     */
    public RegisterCarsPurchased(List<Car> carsSold)
    {
        this.carsSold = carsSold;
    }

    /**
     * Calculates and displays the revenue generated by cars with specific car type.
     * @param characteristic The car type  of the cars for which revenue is to be calculated.
     */
    public void showRevenue(String characteristic)
    {
        
        int numCarsSold = 0;
        double revenue = 0;

        for (Car car : carsSold) {
            if (car.getCarType().equalsIgnoreCase(characteristic)) {
                numCarsSold++;
                revenue += car.getPrice();
            }
        }

        if (numCarsSold == 0) {
            System.out.println("No cars of type " + characteristic + " were sold.");
        } else {
            System.out.println();
            System.out.println("Total number of " + characteristic + " cars sold: " + numCarsSold);
            System.out.println("Total revenue from " + characteristic + " cars: $" + revenue);
        }
        
    }

    /**
     * Calculates and displays the revenue generated by cars with specific ID.
     * 
     * @param characteristic The ID of the cars for which revenue is to be calculated.
     */
    public void showRevenue(int characteristic)
    {
        int numCarsSold = 0;
        double revenue = 0;

        for (Car car : carsSold) {
            if (car.getID() == characteristic) {
                numCarsSold++;
                revenue += car.getPrice();
            }
        }

        if (numCarsSold == 0) {
            System.out.println("No cars with ID " + characteristic + " were sold.");
        } else {
            System.out.println();
            System.out.println("Total number of cars sold with ID " + characteristic + ": " + numCarsSold);
            System.out.println("Total revenue from cars with ID " + characteristic + ": $" + revenue);
        }
    }

}
